# Generated by Django 2.2.3 on 2019-07-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190724_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=264, unique=True)),
                ('year_of_release', models.PositiveIntegerField()),
                ('plot', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('actor', models.ManyToManyField(to='app.Actor')),
            ],
        ),
        migrations.DeleteModel(
            name='Mov',
        ),
    ]
