# Generated by Django 2.2.3 on 2019-07-24 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_moviedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.PositiveIntegerField()),
                ('plot', models.TextField(max_length='1024')),
                ('image', models.ImageField(upload_to='images/')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Movi', unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MovieDetails',
        ),
    ]
