# Generated by Django 2.2.3 on 2019-07-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190726_0646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tvshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tvshow', models.CharField(max_length=264, unique=True)),
                ('lang', models.CharField(choices=[('ENG', 'English'), ('TEL', 'Teleugu'), ('HIN', 'Hindhi')], max_length=3)),
                ('gener', models.CharField(choices=[('Act', 'Action'), ('Adv', 'Adventure'), ('Ani', 'Animation'), ('Com', 'Comedy'), ('Cri', 'Crime'), ('Dra', 'Drama'), ('Fam', 'Family'), ('Fan', 'Fantasy'), ('Hor', 'Horror'), ('Mys', 'Mystrey'), ('Thr', 'Thriller'), ('Sci', 'Sci-fi')], max_length=3)),
                ('status', models.CharField(choices=[('RA', 'Recently Added'), ('TR', 'Top Rated'), ('MW', 'Most Watched')], max_length=2)),
                ('release_date', models.DateField()),
                ('plot', models.TextField(max_length=1024)),
                ('tvshow_image', models.ImageField(upload_to='media')),
                ('tv_actor', models.ManyToManyField(to='app.Actor')),
            ],
        ),
    ]
